In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import itertools
import snscrape.modules.twitter as sntwitter
import plotly.graph_objects as go
from datetime import datetime

In [2]:
# Noting the time it takes to scrape 50000 tweets

start_time = datetime.now()

#Creating dataframe called 'data' and storing the tweets from May 1st 2021 to 30th Juy 2021 for 'Vaccine'
tweets = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper('"#water since:2021-01-01 until:2022-04-08 near:"Cape Town"').get_items(),50000))

end_time = datetime.now()

# Printing the time taken to scrape these tweets
print('Duration: {} '.format(end_time - start_time))

Duration: 0:05:33.934626

In [3]:
tweets.head()

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/__sandla__/status/15122163...,2022-04-07 23:50:53+00:00,"@Ori_RSA So many people are buying water, i th...","@Ori_RSA So many people are buying water, i th...",1512216370800381954,"{'username': '__sandla__', 'id': 1024367262986...",1,1,2,0,...,None,None,None,1.512215e+18,"{'username': 'Ori_RSA', 'id': 2428664117, 'dis...","[{'username': 'Ori_RSA', 'id': 2428664117, 'di...",None,None,None,None
1,https://twitter.com/Ori_RSA/status/15122149713...,2022-04-07 23:45:19+00:00,"@__sandla__ This was in keurboomstrand, I was ...","@__sandla__ This was in keurboomstrand, I was ...",1512214971358318596,"{'username': 'Ori_RSA', 'id': 2428664117, 'dis...",2,0,0,0,...,None,None,None,1.512215e+18,"{'username': '__sandla__', 'id': 1024367262986...","[{'username': '__sandla__', 'id': 102436726298...",None,None,None,None
2,https://twitter.com/AluttaYedwa/status/1512214...,2022-04-07 23:45:11+00:00,At my best friends house and using a water bot...,At my best friends house and using a water bot...,1512214936990142464,"{'username': 'AluttaYedwa', 'id': 113821549565...",0,0,1,0,...,None,None,None,NaN,None,None,None,None,None,None
3,https://twitter.com/__sandla__/status/15122145...,2022-04-07 23:43:46+00:00,@Ori_RSA I see everyone buying water in cape t...,@Ori_RSA I see everyone buying water in cape t...,1512214581313167364,"{'username': '__sandla__', 'id': 1024367262986...",1,1,5,0,...,None,None,None,1.512214e+18,"{'username': 'Ori_RSA', 'id': 2428664117, 'dis...","[{'username': 'Ori_RSA', 'id': 2428664117, 'di...",None,None,None,None
4,https://twitter.com/shaunoakes/status/15122015...,2022-04-07 22:52:04+00:00,@nollynm_again you should be cancelled because...,@nollynm_again you should be cancelled because...,1512201569705594880,"{'username': 'shaunoakes', 'id': 11793062, 'di...",1,0,1,0,...,None,None,None,1.512065e+18,"{'username': 'shaunoakes', 'id': 11793062, 'di...","[{'username': 'nollynm_again', 'id': 140806524...",None,None,None,None

In [4]:
tweets.shape, tweets.columns

((3363, 27),
 Index(['url', 'date', 'content', 'renderedContent', 'id', 'user', 'replyCount',
        'retweetCount', 'likeCount', 'quoteCount', 'conversationId', 'lang',
        'source', 'sourceUrl', 'sourceLabel', 'outlinks', 'tcooutlinks',
        'media', 'retweetedTweet', 'quotedTweet', 'inReplyToTweetId',
        'inReplyToUser', 'mentionedUsers', 'coordinates', 'place', 'hashtags',
        'cashtags'],
       dtype='object'))

In [ ]:
tweets.to_csv('water_capetown.csv')