In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import itertools
import snscrape.modules.twitter as sntwitter
import plotly.graph_objects as go
from datetime import datetime

In [6]:
# Noting the time it takes to scrape 50000 tweets

start_time = datetime.now()

#Creating dataframe called 'data' and storing the tweets from May 1st 2021 to 30th Juy 2021 for 'Vaccine'
tweets = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper('"no water since:2021-01-01 until:2022-04-08 near:"Cape Town"').get_items(),10000))

end_time = datetime.now()

# Printing the time taken to scrape these tweets
print('Duration: {} '.format(end_time - start_time))

Duration: 0:00:18.814248

In [7]:
tweets.head()

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/dani_ray_george/status/151...,2022-04-07 19:46:48+00:00,@JHBWater What is happening in Morningside and...,@JHBWater What is happening in Morningside and...,1512154947407781891,"{'username': 'dani_ray_george', 'id': 32752876...",0,0,0,0,...,None,None,None,NaN,None,"[{'username': 'JHBWater', 'id': 244959564, 'di...",None,None,None,None
1,https://twitter.com/dynagbnnmm/status/15121195...,2022-04-07 17:26:11+00:00,@MoT_1972 @SeeYanda Ok I understand SA is not ...,@MoT_1972 @SeeYanda Ok I understand SA is not ...,1512119561235185666,"{'username': 'dynagbnnmm', 'id': 9985161717911...",2,0,1,0,...,None,None,None,1.512116e+18,"{'username': 'MoT_1972', 'id': 369614868, 'dis...","[{'username': 'MoT_1972', 'id': 369614868, 'di...",None,None,None,None
2,https://twitter.com/5ReeceSwartz5/status/15120...,2022-04-07 12:48:18+00:00,This country been through the most\n- No water...,This country been through the most\n- No water...,1512049629298413570,"{'username': '5ReeceSwartz5', 'id': 748749020,...",0,0,1,0,...,None,None,None,NaN,None,None,None,None,None,None
3,https://twitter.com/hills007/status/1511979167...,2022-04-07 08:08:19+00:00,@CityofCT Please advise what is happening with...,@CityofCT Please advise what is happening with...,1511979167335817219,"{'username': 'hills007', 'id': 764829104638160...",1,0,0,0,...,None,None,None,NaN,None,"[{'username': 'CityofCT', 'id': 132437983, 'di...",None,None,None,None
4,https://twitter.com/Lukhokhanya/status/1511599...,2022-04-06 06:58:55+00:00,@zsimayi Water scarcity is a shame in SA and I...,@zsimayi Water scarcity is a shame in SA and I...,1511599315013505025,"{'username': 'Lukhokhanya', 'id': 446860858, '...",1,0,1,0,...,None,None,None,1.511597e+18,"{'username': 'zsimayi', 'id': 2722891763, 'dis...","[{'username': 'zsimayi', 'id': 2722891763, 'di...",None,None,None,None

In [8]:
tweets.shape, tweets.columns

((96, 27),
 Index(['url', 'date', 'content', 'renderedContent', 'id', 'user', 'replyCount',
        'retweetCount', 'likeCount', 'quoteCount', 'conversationId', 'lang',
        'source', 'sourceUrl', 'sourceLabel', 'outlinks', 'tcooutlinks',
        'media', 'retweetedTweet', 'quotedTweet', 'inReplyToTweetId',
        'inReplyToUser', 'mentionedUsers', 'coordinates', 'place', 'hashtags',
        'cashtags'],
       dtype='object'))

In [ ]:
tweets.to_csv('no_water_capetown.csv')